name    'propertybase-openresty'
version '0.1.0'
author 'Leif Gensert'
license 'MIT'
summary 'Manifest to install openresty distribution of nginx'
description 'Installs the current openresty distribution from source'
project_page 'http://openresty.org/'